In [1]:
from pathlib import Path
import sys

In [2]:
sys.path

['/home/uib/miniconda3/envs/vpf_env/lib/python310.zip',
 '/home/uib/miniconda3/envs/vpf_env/lib/python3.10',
 '/home/uib/miniconda3/envs/vpf_env/lib/python3.10/lib-dynload',
 '',
 '/home/uib/miniconda3/envs/vpf_env/lib/python3.10/site-packages']

In [3]:
src_path = Path("../src").resolve()
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

In [4]:
sys.path

['/home/uib/miniconda3/envs/vpf_env/lib/python310.zip',
 '/home/uib/miniconda3/envs/vpf_env/lib/python3.10',
 '/home/uib/miniconda3/envs/vpf_env/lib/python3.10/lib-dynload',
 '',
 '/home/uib/miniconda3/envs/vpf_env/lib/python3.10/site-packages',
 '/home/uib/proyectos/VPFTaxoClass/src']

In [5]:
from vpf_classifier.parsers.fasta_parser import FastaParser

In [6]:
import os
print("Working directory:", os.getcwd())

Working directory: /home/uib/proyectos/VPFTaxoClass/notebooks

In [7]:
fasta_path = Path("../data/raw/test_inputs/mini_test.fna")

In [8]:
parser = FastaParser(fna_path=fasta_path)

In [9]:
df = parser.parse_fasta_to_dataframe()
print(f"[✔] FASTA parsed. N sequences: {len(df)}")

[✔] FASTA parsed. N sequences: 5

In [10]:
df

,Accession,Description,Sequence,Length
0,EF534708.1,,ACCGGATGGCCGCGGGATTTTTCTTATCTGCTACGTGGCGAAATCG...,2571
1,HM566153.1,,ACACAAAGCTCCCTGAAGATTTAATAACGAAGAAAACAAACATGTC...,1729
2,KX100121.1,,AGTAGTGTACTCCACACTAATAACTTTCAAACTTTGGTAAACTTGA...,950
3,KJ578788.1,,AGTGAAATACCTCCCTTTTGTGGATTTGTCTGTTTGTCGACTTTTT...,29428
4,KU160650.1,,ATGGTAGAGGGGTCAGCGTAGGGGTTTTTTCCTTTGTTTCAACAAA...,46723

In [11]:
faa_path = parser.run_prodigal()
print(f"[✔] Prodigal output: {faa_path}")

[INFO] Prodigal output already found at /home/uib/proyectos/VPFTaxoClass/data/raw/prodigal_output/MSL33
[✔] Prodigal output: /home/uib/proyectos/VPFTaxoClass/data/raw/prodigal_output/MSL33/output.faa

In [12]:
# Ejecutar HMMER (si es necesario)
# parser.run_hmmer(num_cpus=4)
print("[✔] HMMER completed successfully.")

[✔] HMMER completed successfully.

In [13]:
from pathlib import Path
import sys
import os

src_path = Path("../src").resolve()
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

In [14]:

os.environ["ICTV_RELEASE"] = "MSL33"  # o MSL35, MSL40, etc.

print()

from vpf_classifier.pipelines.pipeline import run_pipeline

sequences_df, proteins_df, vpfs_df = run_pipeline(e_value_threshold=1e-3, num_cpus=6)

[PIPELINE] Starting run for ICTV release :MSL33
[STEP 1] Pasing FASTA file...
[STEP 2] Running Prodigal (or reusing previous output)...
[WARNING] Multiple .faa files found in /home/uib/proyectos/VPFTaxoClass/data/raw/prodigal_output/MSL33. Using: VMR_08-201218_MSL33VMRb33.faa
[STEP 3] Running HMMER (if needed) and parsing .tbl hits...
[INFO] Existing HMMER output found: 10 .tbl files
[INFO] Parsing HMMER .tbl files...
[INFO] Filtered HMM hits by e-value < 0.001: 1044785 / 2769725 kept

TypeError: 'dict' object is not callable

In [3]:
sequences_df

,Accession,Description,Sequence,Length
0,AB000403.1,Tenuivirus oryzabrevis genomic RNA5 for nucleo...,ACACAAAGTCCTGGGCAATTATAGCAAAACAACACCTTCTTTAAGT...,2704
1,AB000404.1,Tenuivirus oryzabrevis genomic RNA6 for 20.6K ...,ACACAAAGTCCTGGGCAATTACAAACAAGAAAAACTTAATTAAATA...,2584
2,AB000851.1,"Akabane virus genomic RNA, viral-complementary...",AGTAGTGAACTCCACTATTAACTACGCATTGCAATGGCAAATCAAT...,858
3,AB000906.1,"Infectious flacherie virus genomic RNA, comple...",TCATATGATAAACCCTGAGCTTTATTGTGTGACCCCCTGAGATTTC...,9650
4,AB000920.1,Milk vetch dwarf C1 alphasatellite gene for vi...,AGCACAGGCGGCCTAGTATTACCCGCCTGTGCTCCCCATCCTTTGC...,1007
...,...,...,...,...
7460,Z69620.1,European brown hare syndrome virus RNA,GTGAAATTATGGCGGTTGCGTCGCGCCCTTGCGGCGTGGCGACTTC...,7442
7461,Z69910.1,"Groundnut rosette virus complete genome, strai...",GGGGGTTTCAACATGGCGACTATAAGGCACATTATGGATTGGCTGC...,4019
7462,Z69993.1,"Tula virus genomic RNA, strain (Tula/Moravia/5...",TAGTAGTAGACTCCGCAAGAAGAAGCAAACACAGAGAAAACTGGAA...,3694
7463,Z73124.1,Sweetpotato mild mottle virus mRNA for polypro...,AAAATAAAAATGATATAGAAAAAATTTGAAAGAAAAGCGTGAATTT...,10818
7464,Z97873.1,Beet soil-borne virus RNA1 for 145 kDa protein...,GTATTATTTTCTCAACGGTTATTTACCAAAGAGAAGATTTCTATAC...,5834

In [4]:
proteins_df

,Accession,Description,Sequence,Length,protein_sequences,protein_accessions,protein_lengths
0,AB000403.1,Tenuivirus oryzabrevis genomic RNA5 for nucleo...,ACACAAAGTCCTGGGCAATTATAGCAAAACAACACCTTCTTTAAGT...,2704,[MSGMNSEEYMVLNTMLQTVGCDAHELLKKTPGCEKAVYLFCCKST...,"[AB000403.1_1, AB000403.1_2, AB000403.1_3, AB0...","[192, 84, 47, 326]"
1,AB000404.1,Tenuivirus oryzabrevis genomic RNA6 for 20.6K ...,ACACAAAGTCCTGGGCAATTACAAACAAGAAAAACTTAATTAAATA...,2584,[MSKSHSDVVGTVSGLNYRLFYDMIPDRISQKLRLREITDPKTCNA...,"[AB000404.1_1, AB000404.1_2]","[180, 326]"
2,AB000851.1,"Akabane virus genomic RNA, viral-complementary...",AGTAGTGAACTCCACTATTAACTACGCATTGCAATGGCAAATCAAT...,858,[MANQFIFNDVPQRNAATFNPDAGYVAFISKYGQQLNFTVARVFFL...,[AB000851.1_1],[234]
3,AB000906.1,"Infectious flacherie virus genomic RNA, comple...",TCATATGATAAACCCTGAGCTTTATTGTGTGACCCCCTGAGATTTC...,9650,[MYELAYKMQDSSCEDPGSSPPNQSVALPRESILSGVLRKNNVAEC...,[AB000906.1_1],[3093]
4,AB000920.1,Milk vetch dwarf C1 alphasatellite gene for vi...,AGCACAGGCGGCCTAGTATTACCCGCCTGTGCTCCCCATCCTTTGC...,1007,[STGGLVLPACAPHPLLPIKGSISLIWSFYQMPTLQGTFWCFTLNF...,[AB000920.1_1],[312]
...,...,...,...,...,...,...,...
7460,Z69620.1,European brown hare syndrome virus RNA,GTGAAATTATGGCGGTTGCGTCGCGCCCTTGCGGCGTGGCGACTTC...,7442,[EIMAVASRPCGVATSVLPAKKPLSFFTDLVGKTPPRCIRAPHTLA...,"[Z69620.1_1, Z69620.1_2]","[2337, 115]"
7461,Z69910.1,"Groundnut rosette virus complete genome, strai...",GGGGGTTTCAACATGGCGACTATAAGGCACATTATGGATTGGCTGC...,4019,[GGFNMATIRHIMDWLRPTFTPLAGVKSRQECIAHYGDDWALMITQ...,"[Z69910.1_1, Z69910.1_2, Z69910.1_3]","[290, 545, 261]"
7462,Z69993.1,"Tula virus genomic RNA, strain (Tula/Moravia/5...",TAGTAGTAGACTCCGCAAGAAGAAGCAAACACAGAGAAAACTGGAA...,3694,[MFCLCLSLLGLLLCWPAATRNLLELKVECPHTIGLGQGIVIGSAE...,"[Z69993.1_1, Z69993.1_2]","[1142, 41]"
7463,Z73124.1,Sweetpotato mild mottle virus mRNA for polypro...,AAAATAAAAATGATATAGAAAAAATTTGAAAGAAAAGCGTGAATTT...,10818,[MGKSKLTYKQCIAKWGKAALEAQNNGSRRSVSVGTHQIAANIFAF...,[Z73124.1_1],[3457]
7464,Z97873.1,Beet soil-borne virus RNA1 for 145 kDa protein...,GTATTATTTTCTCAACGGTTATTTACCAAAGAGAAGATTTCTATAC...,5834,[VLFSQRLFTKEKISIPLILKSLLFSNKSFHITGLSFYFYENSTME...,"[Z97873.1_1, Z97873.1_2, Z97873.1_3]","[1314, 479, 53]"

In [5]:
vpfs_df

,Accession,hmms_hits,scores,evalues,protein_accessions,cluster_nums,Description,Sequence,Length,hmms_conteos
0,AB000403.1,[GENOMAD.111973.VV],[49.6],[3.1e-13],[AB000403.1_4],[0],Tenuivirus oryzabrevis genomic RNA5 for nucleo...,ACACAAAGTCCTGGGCAATTATAGCAAAACAACACCTTCTTTAAGT...,2704,<Compressed Sparse Row sparse matrix of dtype ...
1,AB000404.1,"[GENOMAD.059971.VV, GENOMAD.031816.CC]","[17.6, 20.3]","[0.00079, 0.00046]","[AB000404.1_1, AB000404.1_1]","[0, 0]",Tenuivirus oryzabrevis genomic RNA6 for 20.6K ...,ACACAAAGTCCTGGGCAATTACAAACAAGAAAAACTTAATTAAATA...,2584,<Compressed Sparse Row sparse matrix of dtype ...
2,AB000851.1,[GENOMAD.135155.VV],[265.2],[3.2e-79],[AB000851.1_1],[0],"Akabane virus genomic RNA, viral-complementary...",AGTAGTGAACTCCACTATTAACTACGCATTGCAATGGCAAATCAAT...,858,<Compressed Sparse Row sparse matrix of dtype ...
3,AB000906.1,"[GENOMAD.000023.VV, GENOMAD.000026.VV, GENOMAD...","[155.4, 35.8, 86.1, 62.4, 82.4, 18.6, 58.1, 47...","[1.9e-45, 3e-09, 1.7e-24, 2.6e-17, 3.2e-23, 0....","[AB000906.1_1, AB000906.1_1, AB000906.1_1, AB0...","[0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, ...","Infectious flacherie virus genomic RNA, comple...",TCATATGATAAACCCTGAGCTTTATTGTGTGACCCCCTGAGATTTC...,9650,<Compressed Sparse Row sparse matrix of dtype ...
4,AB000920.1,"[GENOMAD.104295.VV, GENOMAD.191933.VP, GENOMAD...","[106.6, 35.4, 41.6, 20.2]","[5.9e-31, 8.1e-09, 7.9e-11, 0.00032]","[AB000920.1_1, AB000920.1_1, AB000920.1_1, AB0...","[0, 1, 0, 0]",Milk vetch dwarf C1 alphasatellite gene for vi...,AGCACAGGCGGCCTAGTATTACCCGCCTGTGCTCCCCATCCTTTGC...,1007,<Compressed Sparse Row sparse matrix of dtype ...
...,...,...,...,...,...,...,...,...,...,...
6462,Z69620.1,"[GENOMAD.000023.VV, GENOMAD.000026.VV, GENOMAD...","[145.3, 54.9, 87.6, 58.4, 70.1, 51.5, 65.1, 18...","[2.2e-42, 5e-15, 5.6e-25, 4.5e-16, 1.7e-19, 6....","[Z69620.1_1, Z69620.1_1, Z69620.1_1, Z69620.1_...","[0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, ...",European brown hare syndrome virus RNA,GTGAAATTATGGCGGTTGCGTCGCGCCCTTGCGGCGTGGCGACTTC...,7442,<Compressed Sparse Row sparse matrix of dtype ...
6463,Z69910.1,"[GENOMAD.000023.VV, GENOMAD.000026.VV, GENOMAD...","[50.8, 206.2, 33.2, 41.5, 21.5, 120.3, 75.8, 4...","[8.9e-14, 7e-61, 2.6e-08, 7e-11, 5.2e-05, 8.5e...","[Z69910.1_2, Z69910.1_2, Z69910.1_2, Z69910.1_...","[0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, ...","Groundnut rosette virus complete genome, strai...",GGGGGTTTCAACATGGCGACTATAAGGCACATTATGGATTGGCTGC...,4019,<Compressed Sparse Row sparse matrix of dtype ...
6464,Z69993.1,"[GENOMAD.086631.VV, GENOMAD.222965.VP, GENOMAD...","[45.9, 120.3, 59.7, 491.9, 162.7, 41.9]","[4.2e-12, 2.3e-35, 1.1e-16, 4.7e-148, 5.2e-48,...","[Z69993.1_1, Z69993.1_1, Z69993.1_1, Z69993.1_...","[0, 0, 0, 0, 0, 0]","Tula virus genomic RNA, strain (Tula/Moravia/5...",TAGTAGTAGACTCCGCAAGAAGAAGCAAACACAGAGAAAACTGGAA...,3694,<Compressed Sparse Row sparse matrix of dtype ...
6465,Z73124.1,"[GENOMAD.000023.VV, GENOMAD.000026.VV, GENOMAD...","[431.5, 63.1, 60.4, 34.4, 83.3, 42.8, 72.2, 34...","[4.3e-129, 1.6e-17, 9.9e-17, 8.3e-09, 1.7e-23,...","[Z73124.1_1, Z73124.1_1, Z73124.1_1, Z73124.1_...","[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",Sweetpotato mild mottle virus mRNA for polypro...,AAAATAAAAATGATATAGAAAAAATTTGAAAGAAAAGCGTGAATTT...,10818,<Compressed Sparse Row sparse matrix of dtype ...
6466,Z97873.1,"[GENOMAD.000026.VV, GENOMAD.000393.VV, GENOMAD...","[104.0, 31.9, 26.7, 38.5, 20.9, 75.0, 23.1, 10...","[6.4e-30, 5.4e-08, 2.5e-06, 5.3e-10, 0.00011, ...","[Z97873.1_2, Z97873.1_2, Z97873.1_2, Z97873.1_...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, ...",Beet soil-borne virus RNA1 for 145 kDa protein...,GTATTATTTTCTCAACGGTTATTTACCAAAGAGAAGATTTCTATAC...,5834,<Compressed Sparse Row sparse matrix of dtype ...